version: 0.2

phases:
  install:
    commands:
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "react-things"
