version: 0.2

phases:
  install:
    commands:
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the React code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./appspec.yml
    - ./react-things/github-finder/src/App.js
    - ./react-things/github-finder/appspec.yml
    - ./react-things/github-finder/scripts/install-npm.sh
    - ./react-things/github-finder/scripts/start_finder.sh
    - ./react-things/github-finder/scripts/stop_finder.sh
